---
- name: Fetch atom repository
  apt_repository: repo=ppa:webupd8team/atom
  sudo: true

- name: Install atom
  apt: name=atom
  sudo: true

- name: Install atom packages
  command: apm install {{item}}
  args:
    creates: /home/{{username}}/.atom/packages/{{item}}
  with_items:
    - file-icons
