---
- name: Install pip
  apt: name=python-pip

- name: Install python headers
  sudo: yes
  apt: name=python-dev

- name: Install pyenv
  command: curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  args:
    creates: /home/{{username}}/.pyenv/

- name: Dev packages
  sudo:  yes
  apt: name={{item}}
  with_items:
    - libxml2-dev
    - libxslt1-dev
